name: Security

on:
  push:
  pull_request:

jobs:

  security:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0', '8.1']

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: date.timezone=UTC

      - name: Set project php-version
        run: |
          echo ${{ matrix.php }} > .php-version

      - uses: actions/cache@v3
        id: cache-composer
        with:
          path: /home/runner/.composer/cache
          key: composer2-php:${{ matrix.php }}-${{ github.sha }}
          restore-keys: composer2-php:${{ matrix.php }}-

      - run: mkdir -p /home/runner/{.composer/cache,.config/composer}
        if: steps.cache-composer.outputs.cache-hit != 'true'

      - name: Composer Github Auth
        run: composer config -g github-oauth.github.com ${{ github.token }}

      - name: Install PHP dependencies
        run: composer update --no-scripts --no-plugins --prefer-dist

      - uses: symfonycorp/security-checker-action@v4
